### PR TITLE
Refactor sphinx to searchd

### PR DESCRIPTION
**Pull request by eguzki**

### CODE REVIEW

**Comment by akostadinov** [comment]
I'm not completely sure issue is not in me because I upgraded from a production operator. What I see though is that after upgrade, the `system-*` deployment configs env variable `THINKING_SPHINX_ADDRESS` still points at `system-sphinx`.

Also as a non-breaking issue, I see useless env variable `THINKING_SPHINX_CONFIGURATION_FILE` set that can be removed from the DCs.

Will try again on Monday with a brand new cluster or Tuesday if I take Monday as day after Easter holiday.

**Comment by eguzki** [comment]
:thinking: 

Good catch!! Thanks for taking the time to test this. I totally missed that. All regarding searchd deployment is upgraded, but references from system-app and system-sidekiq deployments must be upgraded. I will implement that. 

I will remove "THINKING_SPHINX_CONFIGURATION_FILE" as well. 

Can you confirm that `THINKING_SPHINX_ADDRESS` is still needed from the sidekiq deployment?

**Comment by eguzki** [comment]
ready for review @akostadinov

**Review by akostadinov — APPROVED** [review]
Thank you!

Upgrade is working now. 

Yes, we need sphinx connection from both - system app and sidekiq.

There is one issue though. That presently sphinx expects volume at `/var/lib/sphinx`. But I'm changing that to `/var/lib/searchd`.

3scale/porta#3317
3scale/searchd@c150f6c433a8c08c04d8fa1cc627877815a7aa3d

**Comment by akostadinov** [comment]
Still sphinx works though, it just loses its configuration as before. But when the nrew builds are done, it should be fine.

**Comment by eguzki** [comment]
@akostadinov Would it make sense to set `THINKING_SPHINX_INDICES_LOCATION` env var from the operator? The operator is the one mounting the volume in the path `/var/lib/searchd`, so it should be the one telling searchd component where to write the index

**Comment by akostadinov** [comment]
No. This is only used during config file generation and has no effect at runtime.

**Pull request merged**
